### ISSUE TITLE
install.sh requires updates

### ISSUE THREAD

**Issue by elschnorro77** [Honey-Pi/HoneyPi#1]
Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Line 79:
apt-get install -y rpi.gpio python-smbus python-setuptools python3-pip
->
apt-get install -y rpi.gpio python-smbus python-setuptools python3-pip libatlas-base-dev

Line 84:
apt-get install -y lighttpd php7.0-cgi
->
apt-get install -y lighttpd php7.1-cgi

[install.sh.txt](https://github.com/Honey-Pi/HoneyPi/files/3864197/install.sh.txt)

**Comment by JavanXD** [comment]
Thank you i will change it.
